// <auto-generated />
using System;
using C1.BuildingManagementSystems.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace C1.BuildingManagementSystems.Migrations
{
    [DbContext(typeof(BmsDbContext))]
    [Migration("20250814052924_init1_1")]
    partial class init1_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("C1.BuildingManagementSystems.Contracts.Models.MetricEntry", b =>
                {
                    b.Property<int>("MetricEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetricEntryId"));

                    b.Property<DateTime>("EntryDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer");

                    b.Property<double>("MetricValue")
                        .HasColumnType("double precision");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MetricEntryId");

                    b.ToTable("MetricEntries");
                });

            modelBuilder.Entity("C1.BuildingManagementSystems.Logging.Model.LogEntry", b =>
                {
                    b.Property<int>("LogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogEntryId"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogEntryId");

                    b.ToTable("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
