// <auto-generated />
using System;
using C1.BuildingManagementSystems.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace C1.BuildingManagementSystems.Migrations
{
    [DbContext(typeof(BmsDbContext))]
    partial class BmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("C1.BuildingManagementSystems.Contracts.Models.MetricEntry", b =>
                {
                    b.Property<int>("MetricEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetricEntryId"));

                    b.Property<int>("MetricType")
                        .HasColumnType("integer");

                    b.Property<double>("MetricValue")
                        .HasColumnType("double precision");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MetricEntryId");

                    b.ToTable("MetricEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
